import { useEffect, useState } from "react";
import { useStore } from "../store";
import { useDebouncedCallback } from "../hooks/useDebouncedCallback";
import { MacroSliders } from "./MacroSliders";
import { LatentMap } from "./LatentMap";
import { MetaEmotionPresets } from "./MetaEmotionPresets";
import { BasisMixer } from "./BasisMixer";
import { BasisBarChart } from "./BasisBarChart";
import { ModeToggle, type UIMode } from "./ModeToggle";

export function EmotionDJPanel() {
  const strength = useStore((s) => s.strength);
  const setStrength = useStore((s) => s.setStrength);
  const mode = useStore((s) => s.mode);
  const setMode = useStore((s) => s.setMode);
  const rewrite = useStore((s) => s.rewrite);
  const shuffle = useStore((s) => s.shuffleLatent);

  const [uiMode, setUIMode] = useState<UIMode>("normal");
  const [localStrength, setLocalStrength] = useState(strength);
  useEffect(() => setLocalStrength(strength), [strength]);

  const debouncedRewrite = useDebouncedCallback(() => void rewrite(), 500);

  return (
    <div className="px-4 lg:px-6 py-4 space-y-4">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div className="max-w-xl">
          <div className="text-xs uppercase tracking-widest text-booth-muted">
            Emotion DJ panel
          </div>
          <p className="text-[11px] text-booth-muted leading-snug">
            The output is generated by editing a 64-dimensional latent emotion
            code before rewriting. Macro emotions and the 2D map are
            <em> projections </em>
            of that code, not the code itself.
          </p>
        </div>
        <ModeToggle
          uiMode={uiMode}
          setUIMode={setUIMode}
          rewriteMode={mode}
          setRewriteMode={(m) => {
            setMode(m);
            debouncedRewrite();
          }}
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
        <div className="lg:col-span-5 rounded-xl bg-booth-panel border border-booth-edge/60 p-4 shadow-booth">
          <MacroSliders />
          <div className="mt-4 space-y-1">
            <div className="flex justify-between text-[11px]">
              <span className="text-booth-ink">Global strength (0.01-0.40)</span>
              <span className="tabular-nums text-booth-muted">
                {localStrength.toFixed(2)}
              </span>
            </div>
            <input
              type="range"
              className="dj"
              min={0.01}
              max={0.4}
              step={0.01}
              value={localStrength}
              onChange={(e) => {
                const v = parseFloat(e.target.value);
                setLocalStrength(v);
                setStrength(v);
                debouncedRewrite();
              }}
            />
          </div>
        </div>

        <div className="lg:col-span-3 rounded-xl bg-booth-panel border border-booth-edge/60 p-4 shadow-booth flex flex-col items-center justify-start">
          <LatentMap />
        </div>

        <div className="lg:col-span-4 rounded-xl bg-booth-panel border border-booth-edge/60 p-4 shadow-booth space-y-4">
          <MetaEmotionPresets />
          {uiMode === "discovery" && (
            <button
              onClick={() => void shuffle()}
              className="w-full px-3 py-2 rounded-lg bg-booth-accent2/20 hover:bg-booth-accent2/30 border border-booth-accent2/40 text-booth-ink text-xs transition"
            >
              ⤳ Shuffle latent direction
            </button>
          )}
          <BasisBarChart />
        </div>
      </div>

      {uiMode === "research" && (
        <div className="rounded-xl bg-booth-panel border border-booth-edge/60 p-4 shadow-booth">
          <BasisMixer />
        </div>
      )}
    </div>
  );
}
